//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public abstract class AbstractMenu
{
	abstract enum MenuMode;

	void Update() {
		int choice = 0;
		if (Input.GetKeyDown(KeyCode.Alpha1)) {
			choice = 1;
		}
		else if (Input.GetKeyDown(KeyCode.Alpha2)) {
			choice = 2;
		}
		else if (Input.GetKeyDown(KeyCode.Alpha3)) {
			choice = 3;
		}
		makeChoice(choice);
	}

	abstract void makeChoice(int choice);

}

